# Generated by Django 3.1.5 on 2021-02-17 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_articles_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(verbose_name='article body'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='article data'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='sphere',
            field=models.ManyToManyField(related_name='article_sphere', to='Main.spheres'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='status',
            field=models.BooleanField(default=False, verbose_name='is_published'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=120, verbose_name='article title'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='topic',
            field=models.CharField(max_length=120, verbose_name='article topic'),
        ),
        migrations.AlterField(
            model_name='spheres',
            name='name',
            field=models.CharField(help_text='Enter a article sphere ', max_length=200, verbose_name='sphare name'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], max_length=255)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Main.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='comment text')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Main.articles', verbose_name='comment article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='Main.comments', verbose_name='parent comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
